---
title: "p8105_hw3_tb2715"
author: "Tess"
date: "10/5/2019"
output: gitbub_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

##Question 1
```{r}
library(p8105.datasets)
data("instacart") 

instacart = 
   janitor::clean_names(instacart) %>%
  drop_na()

#identify number of aisles
instacart %>%
  count(aisle_id) 

#arrange aisles by number of goods in an aisle
instacart %>%
  group_by(aisle_id) %>%
  summarize(n_obs = n()) %>%
  arrange(desc(n_obs))

#plot of aisles with more than 10,000 items. FIX THIS.  
instacart %>%
  group_by(aisle_id) %>%
  summarize(n_obs = n()) %>% 
  filter(n_obs > 10000) %>%
  ggplot(aes(x = aisle_id, y = n_obs)) +
  geom_col() 

#table of the most popular items “baking ingredients”, “dog food care”, and “packaged vegetables fruits”
instacart_1 =
instacart %>%
  filter(aisle == "baking ingredients" | aisle == "dog food care"| aisle == "packed vegetables fruits") %>%
  group_by(aisle, product_name) %>%
  summarize(n_obs = n()) %>%
  arrange(desc(n_obs))

  pivot_wider(
    names_from = aisle, 
    values_from = product_name
  )
  
#table of the mean hour of the day when Pink Lady apples and Coffee are bought each day of the week
instacart %>%
  filter(product_name == "Pink Lady Apple" | product_name == "Coffee Ice Cream") %>%
   mutate(order_dow = recode(order_dow, "0" = "Mon", 
                                "1" = "Tues", 
                                "2" = "Weds", 
                                "3" = "Thurs", 
                                "4" = "Fri", 
                                "5" = "Sat",
                                "6" = "Sun")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour_of_day = mean(order_hour_of_day)) %>%
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour_of_day
  ) 
  ##instacart[c("Mon", "Tues", "Weds", "Thurs", "Fri", "Sat", "Sun")]
 
  
```

There are 134 aisles in this data set. Aisles 83, 24, 123, and 120 have the most items ordered from them. 